### ISSUE TITLE
brightness group=0

### ISSUE THREAD

**Issue by Lyr3x** [Nesurion/milight-daemon#12]
We cant set the brightness for group 0. 
`http://jane:8080/brightness?group=0&level=100` will be accepted but dont change the brightness. Also i recognized huger delays for group=0 brightness ~230ms. Changing brightness for group=[1-4] works fine with ~1-15ms delay

**Comment by Nesurion** [comment]
Can't reproduce this for my setup.
In terms of delay, are you running the `all-group-sleep` branch? if so: there is a intended delay of a few ms to get the sending of commands more stable.

Could build master or download 0.0.2 and try again?

**Comment by Lyr3x** [comment]
Its working
