### ISSUE TITLE
Script Runs, but lights not changing

### ISSUE THREAD

**Issue by ryanlaux** [Nesurion/milight-daemon#14]
Attempting to run the milight-daemon in terminal on osx. I've configured the config file with the IP and a port, and when I run the file in terminal I get the following when I send an HTTP request: 

GIN] 2015/12/08 - 05:56:43 | 404 |       6.895µs | 127.0.0.1:60024 |   GET     /off

However, the bulb doesn't turn off or change in any way. Any suggestions?

**Comment by Lyr3x** [comment]
You need to configure your ip:port with the IP port from your bridge. Did
you?

**Comment by ryanlaux** [comment]
Where do I find that? In the config file I left the port at 8080, the wifi bridge port is the default 8899

**Comment by ryanlaux** [comment]
Changing the config port number to 8899 doesn't work either

**Comment by Lyr3x** [comment]
Use port 8080 to reach the daemon via port 8080. you just need to find out
the IP of your milight bridge (e.g. take a look at your Routers interface).
Set the IP to your bridge IP in the config file. You can use the daemon
than with:
<IP of daemon host>:<8080>/off...

**Comment by ryanlaux** [comment]
Yes I had edited the config file with the correct IP as follows:

{
    "port": 8080,
    "bridge": "192.168.0.25"
}

and I've confirmed the IP works from my mac with some other python script I have, but your script isn't working oddly

**Comment by Lyr3x** [comment]
GIN] 2015/12/08 - 05:56:43 | 404 | 6.895µs |127.0.0.1:60024 | GET /off

You need to execute a HTTP POST.

**Comment by ryanlaux** [comment]
Works! Thank you

**Comment by Lyr3x** [comment]
Cool! Then close here.
